server:
  port: 8081


spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/springtest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://127.0.0.1:3306/springtest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url:  jdbc:mysql://localhost:3306/springtest?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: "030230"
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.example.startpractice.dao.entity
  mapper-locations: classpath:mapper/*.xml
  #开启mybatis的二级缓存
  configuration:
    cache-enabled: true

logging:
  file:
    name: logs/info.log